function status = nc_gen_nam_data(file_name,ni,nj,nt,var_name)

  % NetCDF creation mode options
%   ncopts = bitor(netcdf.getConstant('CLASSIC_MODEL'),   ...
%                  netcdf.getConstant('NETCDF4')          ...
%                 );
  ncopts = netcdf.getConstant('NETCDF4');
            
  % Create the NetCDF   
  if(exist(file_name,'file')==2); delete(file_name); end
  ncid = netcdf.create(file_name,ncopts);
  
  % Global attributes
  netcdf.putAtt(ncid,-1,'type','DATA file');
  netcdf.putAtt(ncid,-1,'source','North American Mesocale (NAM) model Analysis (ANL) product');
  netcdf.putAtt(ncid,-1,'history',['generated by nc_gen_nam_data.m on ' datestr(now)]);
  netcdf.putAtt(ncid,-1,'grid','218');

  % Dimensions
  dimid = [];
  dimid(end+1) = netcdf.defDim(ncid,'ni',ni);
  dimid(end+1) = netcdf.defDim(ncid,'nj',nj);
  dimid(end+1) = netcdf.defDim(ncid,'nt',nt);

  % Variables
  varid = [];
  for i=1:numel(var_name)
  switch var_name{i}
      
    case 'winds'
      varid(end+1) = netcdf.defVar(ncid,'wind_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'Uair','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','10m eastward wind velocity');
        netcdf.putAtt(ncid,varid(end),'units','meters second-1');
      varid(end+1) = netcdf.defVar(ncid,'Vair','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','10m northward wind velocity');
        netcdf.putAtt(ncid,varid(end),'units','meters second-1');
          
    case 'Pair'
      varid(end+1) = netcdf.defVar(ncid,'pair_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'Pair','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','surface air pressure reduced to MSL');
        netcdf.putAtt(ncid,varid(end),'units','mbar');   
          
    case 'Tair'
      varid(end+1) = netcdf.defVar(ncid,'tair_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'Tair','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','10m air temperature');
        netcdf.putAtt(ncid,varid(end),'units','degrees Celsius');        
          
    case 'Qair'
      varid(end+1) = netcdf.defVar(ncid,'qair_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'Qair','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','10m air relative humidity');
        netcdf.putAtt(ncid,varid(end),'units','percentage');  
          
      case 'Cfra'
      varid(end+1) = netcdf.defVar(ncid,'cloud_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'Cfra','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','cloud fraction');
        netcdf.putAtt(ncid,varid(end),'units','fraction');  
          
      case 'rain'
      varid(end+1) = netcdf.defVar(ncid,'rain_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'rain','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','rainfall rate');
        netcdf.putAtt(ncid,varid(end),'units','kilogram meters+2 seconds-1');  
          
    case 'lwrad'
      varid(end+1) = netcdf.defVar(ncid,'lrf_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'lwrad_down','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','surface downward longwave radiation');
        netcdf.putAtt(ncid,varid(end),'units','Watts meters+2');
      varid(end+1) = netcdf.defVar(ncid,'lwrad_up','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','surface upward longwave radiation');
        netcdf.putAtt(ncid,varid(end),'units','Watts meters+2');
          
    case 'swrad'
      varid(end+1) = netcdf.defVar(ncid,'srf_time','double',dimid(3));
        netcdf.putAtt(ncid,varid(end),'units','days since beginning of this month');
      varid(end+1) = netcdf.defVar(ncid,'swrad_down','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','surface downward shortwave radiation');
        netcdf.putAtt(ncid,varid(end),'units','Watts meters+2');
      varid(end+1) = netcdf.defVar(ncid,'swrad_up','double',[dimid(1) dimid(2) dimid(3)]);
        netcdf.putAtt(ncid,varid(end),'long_name','surface upward shortwave radiation');
        netcdf.putAtt(ncid,varid(end),'units','Watts meters+2');
          
    otherwise
      error(['Unknown variable name: ' var_name{i}]);
  end  
  end
  clear i;
 
  % End definitions and close
  netcdf.endDef(ncid);
  netcdf.close(ncid);
  
  % Success!
  status = 1;

end