function status = nc_gen_nam_grid(filename,ni,nj)

  % NetCDF creation mode options
  ncopts = bitor(netcdf.getConstant('CLASSIC_MODEL'),   ...
                 netcdf.getConstant('NETCDF4')          ...
                );
  % Create the NetCDF          
  ncid = netcdf.create(filename,ncopts);
  
  % Global attributes
  netcdf.putAtt(ncid,-1,'type','GRID file');
  netcdf.putAtt(ncid,-1,'source','North American Mesocale (NAM) model Analysis (ANL) product');
  netcdf.putAtt(ncid,-1,'history',['generated by nc_gen_nam_grid.m on ' datestr(now)]);
  netcdf.putAtt(ncid,-1,'grid','218');
  
  % Dimensions
  dimid = [];
  dimid(end+1) = netcdf.defDim(ncid,'ni',ni);
  dimid(end+1) = netcdf.defDim(ncid,'nj',nj);
  
  % Variables
  varid = [];
  
  varid(end+1) = netcdf.defVar(ncid,'x','double',dimid(1));
    netcdf.putAtt(ncid,varid(end),'long_name','x-position');
    netcdf.putAtt(ncid,varid(end),'units',    'kilometers east');
    
  varid(end+1) = netcdf.defVar(ncid,'y','double',dimid(2));
    netcdf.putAtt(ncid,varid(end),'long_name','y-position');
    netcdf.putAtt(ncid,varid(end),'units',    'kilometers north');
  
  varid(end+1) = netcdf.defVar(ncid,'lon','double',[dimid(1) dimid(2)]);
    netcdf.putAtt(ncid,varid(end),'long_name','longitude');
    netcdf.putAtt(ncid,varid(end),'units',    'degrees east');
    
  varid(end+1) = netcdf.defVar(ncid,'lat','double',[dimid(1) dimid(2)]);
    netcdf.putAtt(ncid,varid(end),'long_name','latitude');
    netcdf.putAtt(ncid,varid(end),'units',    'degrees north');
    
  varid(end+1) = netcdf.defVar(ncid,'mask','double',[dimid(1) dimid(2)]);
    netcdf.putAtt(ncid,varid(end),'long_name', 'land/sea mask');
    netcdf.putAtt(ncid,varid(end),'land value','0');
    netcdf.putAtt(ncid,varid(end),'sea value', '1');
    
  varid(end+1) = netcdf.defVar(ncid,'i0','NC_SHORT',[]);
    netcdf.putAtt(ncid,varid(end),'long_name','index 1 start');
    
  varid(end+1) = netcdf.defVar(ncid,'j0','NC_SHORT',[]);
    netcdf.putAtt(ncid,varid(end),'long_name','index 2 start');
  
  % End definitions and close
  netcdf.endDef(ncid);
  netcdf.close(ncid);
  
  % Success!
  status = 1;
  
end
